### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by aadesh1010** [Shymoney/Sports-betting-web-app#3]
betslip.php
deposit.php
file missing

**Comment by Shymoney** [comment]
files will be updated soon

**Comment by Shymoney** [comment]
you can contribute to the project @aadesh1010

**Comment by lbsparks** [comment]
HI mate .. Thanks for the project.. I am working on a few stuff and i will add some other features into it

**Comment by Shymoney** [comment]
All files have been updated. follow the instructions on the README file to get started.
